#!/bin/sh

selected=$(find  ~/projects ~/ ~/courses -mindepth 1 -maxdepth 1 -type d | fzf)

if [ -z $selected ]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if ! tmux has-session -t=$selected_name 2> /dev/null
then
    tmux new-session -ds $selected_name -c $selected
fi

# Use sv function to load venv if it exists
tmux send-keys -t $selected_name "sv" C-m C-l

if [ -z $TMUX ]
then
    tmux attach-session -t $selected_name
else
    tmux switch-client -t $selected_name
fi


