# import = ["/home/thibault/.config/alacritty/themes/afterglow.toml"]
# import = ["/home/thibault/.config/alacritty/themes/ayu_light.toml"]
# import = ["/home/thibault/.config/alacritty/themes/catppucin-frappe.toml"]
import = ["/home/thibault/.config/alacritty/themes/catppuccin_latte.toml"]

[font]
size = 12.0

[font.normal]
family = "JetBrainsMonoNerdFont"

[window]
decorations = "full"
startup_mode = "Maximized"

[window.padding]
x = 10
y = 10
